title: Hamed Yaghoobian
email: hamedyaghoobian@muhlenberg.edu
description: >-
  Assistant Professor of Computer Science
baseurl: ""
url: "https://hamedyaghoobian.github.io"

# Social links (uncomment and add your links)
github_username: hamedyaghoobian
google_scholar: https://scholar.google.com/citations?user=6626541213499116714&hl=en

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - pedagogy.md
  - student-research.md
  - public-interactions.md
  - news.md
  - tools.md
  - persian-poetry.md

# Custom variables
google_analytics: G-R39YNYB88S  # Replace with your Measurement ID
